language: node_js
script: npm run $TEST_SUITE
sudo: false
cache:
  directories:
    - node_modules
node_js:
  - 10
env:
  matrix:
    - TEST_SUITE=lint
    - TEST_SUITE=test
    - TEST_SUITE=size-limit
